### ISSUE TITLE
Comment on logging

### ISSUE THREAD

**Issue by hobbyquaker** [dersimn/node-mqtt-smarthome#2]
https://github.com/dersimn/node-mqtt-smarthome/blob/df548d6adb1097b8fb9ff792e7281f959cb49054/index.js#L13

I would suggest to create a possibility to supply a custom logger via options.

**Comment by dersimn** [comment]
That's what the next lines are for 😁.

You can either specify a logger with [this](https://github.com/dersimn/node-mqtt-smarthome/blob/df548d6adb1097b8fb9ff792e7281f959cb49054/test.js#L4) or it will choose `yalm` in silent mode (because I don't think libraries should output anything unless the developer want them to. We could also implement a dummy logger that consumes less memory.

**Comment by hobbyquaker** [comment]
ah i see. Perhaps also a possibility: as the lib is already an event emitter you could just emit log events.
